### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by fuzzyroddis** [Homebrew/homebrew.github.io#98] opened 2016-01-30 00:41 UTC
Previously discussed here:
https://github.com/Homebrew/homebrew.github.io/issues/76
https://github.com/Homebrew/homebrew.github.io/issues/25

From my understanding the issue is cost and complexity.

https://support.cloudflare.com/hc/en-us/articles/203663694-How-do-I-enable-free-Universal-SSL-with-Github-

Cloudflare will do HTTPS for free with a simple dns change and no need to move away from Github pages.

**Comment by DomT4** [comment] 2016-01-30 03:22
You missed further discussion over in the Homebrew repo. This was possible for a while (I set up a test page using an identical setup to the Homebrew homepage) but Cloudflare _seemingly_ later moved to block it and it no longer functioned.

We contacted them to check and were told SSL on GitHub Pages using a custom domain was a dead end at the present time.

At last check that hadn't changed.

**Comment by fuzzyroddis** [comment] 2016-01-31 08:49
That's a shame! How long did it take till it was blocked?

I have a copy of brew.sh working here https://uow.ninja

**Comment by mikemcquaid** [comment] 2016-01-31 12:42
@fuzzyroddis The issue isn't setting up CloudFlare but the interaction between setting up CloudFlare and the other services on brew.sh (managed by DNSimple). I'd still like to try and get this working.

**Comment by fuzzyroddis** [comment] 2016-02-01 09:49
Cloudflare will take over DNS, will this be problematic?
GitHub has declared the test account I used for https://uow.ninja as "not human" so that's why it isn't working but Cloudflare seems to be ok with it :)

I use this:

CNAME
uow.ninja	is an alias of testydvek.github.io	(Cloudflare)
CNAME
www	is an alias of testydvek.uow.ninja	(Cloudflare)

I'd love to help get this up and running

**Comment by mikemcquaid** [comment] 2016-02-01 09:57
> Cloudflare will take over DNS, will this be problematic?

Yes, we have stuff on `bot.brew.sh` and email addresses we need to use.

**Comment by fuzzyroddis** [comment] 2016-02-04 20:45
Does DNSSimple offer provide a service that is specific to them that you require?

On the test domain I setup dns records that match that of brew.sh

Brew.sh
https://toolbox.googleapps.com/apps/dig/#A/bot.brew.sh
https://toolbox.googleapps.com/apps/dig/#MX/brew.sh

uow.ninja
https://toolbox.googleapps.com/apps/dig/#A/bot.uow.ninja
https://toolbox.googleapps.com/apps/dig/#MX/uow.ninja

The grey cloud with an arrow going over it icon 
<img width="68" alt="screen shot 2016-02-05 at 7 42 34 am" src="https://cloud.githubusercontent.com/assets/2271265/12829035/1567418a-cbdc-11e5-876d-3463032bd42a.png">
Indicates it is not proxied by Cloudflare and so it's traffic goes directly to your host and will work just like it did before.

According to https://support.dnsimple.com/articles/cloudflare-service/#universal-ssl-limitations
You'll need to change your name servers to Cloudflare's to use Universal HTTPS.

Here is my setup on Cloudflare.
<img width="970" alt="screen shot 2016-02-05 at 7 40 09 am" src="https://cloud.githubusercontent.com/assets/2271265/12828984/b952600a-cbdb-11e5-9d61-49a72f842554.png">

Sorry for the late response I've sadly been really busy. Happy to help make this happen though!

**Comment by mikemcquaid** [comment] 2016-02-05 19:48
I need to try and figure this out at some point.

**Comment by stevenatwork** [comment] 2016-02-16 03:06
Thanks :+1:

**Comment by konklone** [comment] 2016-07-03 19:54
Please do try and figure this out. It only takes one network rule by a hacked router or malicious ISP to rewrite brew.sh's delivered cURL command to pull from a malicious URL that users won't notice (e.g. some variant of `raw.githubusercontent.com`), with a script that's identical up to the point that the user types in their password for `sudo` access, and then owns their machine. 

And users will, rightly, blame brew for the attack -- if they ever learn that they were attacked at all.

**Comment by DomT4** [comment] 2016-07-03 20:01
The desire to get `brew.sh` covered with SSL/TLS is mutual. This isn't being ignored, even if public activity on getting there appears that way.

**Comment by konklone** [comment] 2016-07-03 20:16
That's awesome to hear, thank you. :+1:

**Comment by scpeters** [comment] 2016-11-07 18:45
DNSimple has a [private beta](https://support.dnsimple.com/articles/letsencrypt/) of [Let's Encrypt](https://letsencrypt.org/). Not sure if that would be useful or not.

**Comment by yegle** [comment] 2017-02-07 04:06
In case you are not aware: Firebase by Google provides free plan to host static website, and automatically provision SSL for custom domain.

https://firebase.google.com/docs/hosting/custom-domain

**Comment by scpeters** [comment] 2017-02-07 07:19
Also, here's the pricing page for Firebase; I'm not sure we'd qualify for the free tier:

* https://firebase.google.com/pricing/

**Comment by MikeMcQuaid** [comment] 2017-02-12 13:59
Fixed by using [Netlify](https://www.netlify.com) which made this all pretty easy.

**Closed by MikeMcQuaid** 2017-02-12 13:59 UTC
